import { defineConfig } from 'vitepress'
import { resolve } from 'path'
const projRoot = resolve(__dirname, '../..')
export default defineConfig({
  title: 'Stellux UI',
  description: 'A Vue 3 based component library for designers and developers',
  base: '/stellux-ui/',
  head: [['meta', { name: 'theme-color', content: '#6366f1' }]],
  vite: { resolve: { alias: {
    'stellux-ui': resolve(projRoot, 'packages/stellux-ui/src'),
    '@stellux/components': resolve(projRoot, 'packages/components/src'),
    '@stellux/hooks': resolve(projRoot, 'packages/hooks/src'),
    '@stellux/utils': resolve(projRoot, 'packages/utils/src'),
    '@stellux/directives': resolve(projRoot, 'packages/directives/src'),
    '@stellux/theme': resolve(projRoot, 'packages/theme')
  }}},
  themeConfig: {
    nav: [{ text: 'Guide', link: '/guide/getting-started' }, { text: 'Components', link: '/components/button' }],
    sidebar: {
      '/guide/': [{ text: 'Basics', items: [{ text: 'Getting Started', link: '/guide/getting-started' }, { text: 'Theme', link: '/guide/theme' }]}],
      '/components/': [
        { text: 'Basic', items: [
            { text: 'Button', link: '/components/button' },
            { text: 'Container', link: '/components/container' },
            { text: 'Layout', link: '/components/layout' },
            { text: 'Icon', link: '/components/icon' },
            { text: 'Link', link: '/components/link' },
            { text: 'Text', link: '/components/text' },
            { text: 'Divider', link: '/components/divider' },
            { text: 'Space', link: '/components/space' },
            { text: 'Scrollbar', link: '/components/scrollbar' },
            { text: 'Splitter', link: '/components/splitter' },
        ]},
        { text: 'Form', items: [
            { text: 'Input', link: '/components/input' },
            { text: 'Form', link: '/components/form' },
            { text: 'Radio', link: '/components/radio' },
            { text: 'Checkbox', link: '/components/checkbox' },
            { text: 'Switch', link: '/components/switch' },
            { text: 'InputNumber', link: '/components/input-number' },
            { text: 'Select', link: '/components/select' },
            { text: 'Rate', link: '/components/rate' },
            { text: 'Slider', link: '/components/slider' },
            { text: 'Autocomplete', link: '/components/autocomplete' },
        ]},
        { text: 'Data Display', items: [            { text: 'Tag', link: '/components/tag' },
            { text: 'Badge', link: '/components/badge' },
            { text: 'Card', link: '/components/card' },
            { text: 'Avatar', link: '/components/avatar' },
            { text: 'Empty', link: '/components/empty' },
            { text: 'Result', link: '/components/result' },
            { text: 'Progress', link: '/components/progress' },
            { text: 'Statistic', link: '/components/statistic' },
            { text: 'Collapse', link: '/components/collapse' },
            { text: 'Skeleton', link: '/components/skeleton' },
            { text: 'Segmented', link: '/components/segmented' },
            { text: 'Timeline', link: '/components/timeline' },
            { text: 'Descriptions', link: '/components/descriptions' },
            { text: 'InfiniteScroll', link: '/components/infinite-scroll' },
            { text: 'Table', link: '/components/table' },
            { text: 'Image', link: '/components/image' },
        ]},
        { text: 'Navigation', items: [            { text: 'Menu', link: '/components/menu' },
            { text: 'Tabs', link: '/components/tabs' },
            { text: 'Breadcrumb', link: '/components/breadcrumb' },
            { text: 'Dropdown', link: '/components/dropdown' },
            { text: 'PageHeader', link: '/components/page-header' },
            { text: 'Steps', link: '/components/steps' },
            { text: 'Affix', link: '/components/affix' },
            { text: 'Backtop', link: '/components/backtop' },
            { text: 'Anchor', link: '/components/anchor' },
        ]},
        { text: 'Feedback', items: [            { text: 'Alert', link: '/components/alert' },
            { text: 'Tooltip', link: '/components/tooltip' },
            { text: 'Popover', link: '/components/popover' },
            { text: 'Dialog', link: '/components/dialog' },
            { text: 'Drawer', link: '/components/drawer' },
            { text: 'Message', link: '/components/message' },
            { text: 'Notification', link: '/components/notification' },
            { text: 'MessageBox', link: '/components/message-box' },
            { text: 'Loading', link: '/components/loading' },
            { text: 'Popconfirm', link: '/components/popconfirm' },
        ]},
        { text: 'Other', items: [            { text: 'Overlay', link: '/components/overlay' },
            { text: 'CollapseTransition', link: '/components/collapse-transition' },
        ]},
      ]
    },
    socialLinks: [{ icon: 'github', link: 'https://github.com/stellux-ui/stellux-ui' }],
    footer: { message: 'Released under the MIT License.', copyright: 'Copyright 2026 Stellux UI' }
  }
})
